/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author sebas
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        opc_RegEnvio = new javax.swing.JMenuItem();
        opcSalida = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        opc_ConsulEnvio = new javax.swing.JMenuItem();
        opc_ConsulCliente = new javax.swing.JMenuItem();
        opc_ConsulMerc = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        opc_RegEnvio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        opc_RegEnvio.setText("Registro Envio");
        opc_RegEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_RegEnvioActionPerformed(evt);
            }
        });
        fileMenu.add(opc_RegEnvio);

        opcSalida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        opcSalida.setMnemonic('x');
        opcSalida.setText("Salida");
        opcSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalidaActionPerformed(evt);
            }
        });
        fileMenu.add(opcSalida);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Consultar");

        opc_ConsulEnvio.setText("Consultar Envio");
        editMenu.add(opc_ConsulEnvio);

        opc_ConsulCliente.setText("Consultar Cliente");
        editMenu.add(opc_ConsulCliente);

        opc_ConsulMerc.setText("Consultar Mercancia");
        opc_ConsulMerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_ConsulMercActionPerformed(evt);
            }
        });
        editMenu.add(opc_ConsulMerc);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");
        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opcSalidaActionPerformed

    private void opc_ConsulMercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_ConsulMercActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc_ConsulMercActionPerformed

    private void opc_RegEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_RegEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc_RegEnvioActionPerformed

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    public JMenu getEditMenu() {
        return editMenu;
    }

    public void setEditMenu(JMenu editMenu) {
        this.editMenu = editMenu;
    }

    public JMenu getFileMenu() {
        return fileMenu;
    }

    public void setFileMenu(JMenu fileMenu) {
        this.fileMenu = fileMenu;
    }

    public JMenu getHelpMenu() {
        return helpMenu;
    }

    public void setHelpMenu(JMenu helpMenu) {
        this.helpMenu = helpMenu;
    }

    public JMenuBar setMenuBar() {
        return menuBar;
    }

    public void setMenuBar(JMenuBar menuBar) {
        this.menuBar = menuBar;
    }

    public JMenuItem getOpcSalida() {
        return opcSalida;
    }

    public void setOpcSalida(JMenuItem opcSalida) {
        this.opcSalida = opcSalida;
    }

    public JMenuItem getOpc_ConsulCliente() {
        return opc_ConsulCliente;
    }

    public void setOpc_ConsulCliente(JMenuItem opc_ConsulCliente) {
        this.opc_ConsulCliente = opc_ConsulCliente;
    }

    public JMenuItem getOpc_ConsulEnvio() {
        return opc_ConsulEnvio;
    }

    public void setOpc_ConsulEnvio(JMenuItem opc_ConsulEnvio) {
        this.opc_ConsulEnvio = opc_ConsulEnvio;
    }

    public JMenuItem getOpc_ConsulMerc() {
        return opc_ConsulMerc;
    }

    public void setOpc_ConsulMerc(JMenuItem opc_ConsulMerc) {
        this.opc_ConsulMerc = opc_ConsulMerc;
    }

    public JMenuItem getOpc_RegEnvio() {
        return opc_RegEnvio;
    }

    public void setOpc_RegEnvio(JMenuItem opc_RegEnvio) {
        this.opc_RegEnvio = opc_RegEnvio;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem opcSalida;
    private javax.swing.JMenuItem opc_ConsulCliente;
    private javax.swing.JMenuItem opc_ConsulEnvio;
    private javax.swing.JMenuItem opc_ConsulMerc;
    private javax.swing.JMenuItem opc_RegEnvio;
    // End of variables declaration//GEN-END:variables

}
